In [1]:
# Importing the required library
import pandas as pd
from Univariate import Univariate

In [2]:
# Loading the dataset
dataset = pd.read_csv("DillibabuSarva_DefectDataset.csv")
dataset

,SHA,cbo,wmc,dit,rfc,lcom,totalMethods,totalFields,nosi,loc,...,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocks,uniqueWordsQty,defect
0,7a955fd6c7de2bd912be544dcfe77f9173a7aa600,5,60,2,55,189,27,5,30,247,...,4,2,47,9,27,5,17,3,191,0
1,000f1ab4780fc9460975791c52597f7c04e15be70,3,10,1,1,9,7,4,1,38,...,0,0,0,22,4,0,4,2,69,0
2,000f1ab4780fc9460975791c52597f7c04e15be71,3,10,1,1,9,7,4,0,38,...,0,0,0,22,4,0,4,2,69,1
3,0024dbdd6ba3cc7797cc0b1ae537dcdc488c4c270,20,59,3,63,189,24,9,4,262,...,0,6,6,14,45,8,41,4,222,0
4,0024dbdd6ba3cc7797cc0b1ae537dcdc488c4c271,21,58,2,61,189,24,9,0,260,...,0,6,6,14,45,8,41,4,222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6047,ffd1ed788cbf10bed00d49d79c7ee44250c36ac11,52,124,12,144,963,110,9,0,804,...,0,0,26,16,32,4,30,6,689,1
6048,ffdf4a3fcccb7489548c6a2ff6af7cebc92a180c0,24,27,2,46,4,8,8,0,126,...,0,1,3,14,27,0,24,3,108,0
6049,ffdf4a3fcccb7489548c6a2ff6af7cebc92a180c1,22,27,1,46,4,8,8,0,126,...,0,1,3,14,27,0,24,3,108,1
6050,ffe7c9989a4553d35fd1d5041d0cece0a673a0c80,3,12,2,12,28,8,0,1,67,...,2,0,0,2,10,0,8,2,36,0
6051,ffe7c9989a4553d35fd1d5041d0cece0a673a0c81,5,11,1,11,21,7,0,0,62,...,2,0,0,1,9,0,7,2,37,1

In [3]:
# Displaying the rows and columns count
dataset.shape

(6052, 23)

In [4]:
quan,qual=Univariate.quanQual(dataset)

In [5]:
quan

['cbo',
 'wmc',
 'dit',
 'rfc',
 'lcom',
 'totalMethods',
 'totalFields',
 'nosi',
 'loc',
 'returnQty',
 'loopQty',
 'comparisonsQty',
 'tryCatchQty',
 'parenthesizedExpsQty',
 'stringLiteralsQty',
 'numbersQty',
 'assignmentsQty',
 'mathOperationsQty',
 'variablesQty',
 'maxNestedBlocks',
 'uniqueWordsQty',
 'defect']

In [6]:
qual

['SHA']

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6052 entries, 0 to 6051
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SHA                   6052 non-null   object
 1   cbo                   6052 non-null   int64
 2   wmc                   6052 non-null   int64
 3   dit                   6052 non-null   int64
 4   rfc                   6052 non-null   int64
 5   lcom                  6052 non-null   int64
 6   totalMethods          6052 non-null   int64
 7   totalFields           6052 non-null   int64
 8   nosi                  6052 non-null   int64
 9   loc                   6052 non-null   int64
 10  returnQty             6052 non-null   int64
 11  loopQty               6052 non-null   int64
 12  comparisonsQty        6052 non-null   int64
 13  tryCatchQty           6052 non-null   int64
 14  parenthesizedExpsQty  6052 non-null   int64
 15  stringLiteralsQty     6052 non-null   int64
 16  numbersQty            6052 non-null   int64
 17  assignmentsQty        6052 non-null   int64
 18  mathOperationsQty     6052 non-null   int64
 19  variablesQty          6052 non-null   int64
 20  maxNestedBlocks       6052 non-null   int64
 21  uniqueWordsQty        6052 non-null   int64
 22  defect                6052 non-null   int64
dtypes: int64(22), object(1)
memory usage: 1.1+ MB

In [8]:
# Display the quantitative dataset
df = dataset[quan]
df

,cbo,wmc,dit,rfc,lcom,totalMethods,totalFields,nosi,loc,returnQty,...,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocks,uniqueWordsQty,defect
0,5,60,2,55,189,27,5,30,247,25,...,4,2,47,9,27,5,17,3,191,0
1,3,10,1,1,9,7,4,1,38,7,...,0,0,0,22,4,0,4,2,69,0
2,3,10,1,1,9,7,4,0,38,7,...,0,0,0,22,4,0,4,2,69,1
3,20,59,3,63,189,24,9,4,262,12,...,0,6,6,14,45,8,41,4,222,0
4,21,58,2,61,189,24,9,0,260,12,...,0,6,6,14,45,8,41,4,222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6047,52,124,12,144,963,110,9,0,804,20,...,0,0,26,16,32,4,30,6,689,1
6048,24,27,2,46,4,8,8,0,126,3,...,0,1,3,14,27,0,24,3,108,0
6049,22,27,1,46,4,8,8,0,126,3,...,0,1,3,14,27,0,24,3,108,1
6050,3,12,2,12,28,8,0,1,67,7,...,2,0,0,2,10,0,8,2,36,0
6051,5,11,1,11,21,7,0,0,62,6,...,2,0,0,1,9,0,7,2,37,1

In [9]:
# Display the dataset columns
df.columns

Index(['cbo', 'wmc', 'dit', 'rfc', 'lcom', 'totalMethods', 'totalFields',
       'nosi', 'loc', 'returnQty', 'loopQty', 'comparisonsQty', 'tryCatchQty',
       'parenthesizedExpsQty', 'stringLiteralsQty', 'numbersQty',
       'assignmentsQty', 'mathOperationsQty', 'variablesQty',
       'maxNestedBlocks', 'uniqueWordsQty', 'defect'],
      dtype='object')

In [10]:
# Display the independent variable data
independent = df[['cbo', 'wmc', 'dit', 'rfc', 'lcom', 'totalMethods', 'totalFields',
       'nosi', 'loc', 'returnQty', 'loopQty', 'comparisonsQty', 'tryCatchQty',
       'parenthesizedExpsQty', 'stringLiteralsQty', 'numbersQty',
       'assignmentsQty', 'mathOperationsQty', 'variablesQty',
       'maxNestedBlocks', 'uniqueWordsQty']]
independent

,cbo,wmc,dit,rfc,lcom,totalMethods,totalFields,nosi,loc,returnQty,...,comparisonsQty,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocks,uniqueWordsQty
0,5,60,2,55,189,27,5,30,247,25,...,9,4,2,47,9,27,5,17,3,191
1,3,10,1,1,9,7,4,1,38,7,...,2,0,0,0,22,4,0,4,2,69
2,3,10,1,1,9,7,4,0,38,7,...,2,0,0,0,22,4,0,4,2,69
3,20,59,3,63,189,24,9,4,262,12,...,16,0,6,6,14,45,8,41,4,222
4,21,58,2,61,189,24,9,0,260,12,...,15,0,6,6,14,45,8,41,4,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6047,52,124,12,144,963,110,9,0,804,20,...,3,0,0,26,16,32,4,30,6,689
6048,24,27,2,46,4,8,8,0,126,3,...,8,0,1,3,14,27,0,24,3,108
6049,22,27,1,46,4,8,8,0,126,3,...,8,0,1,3,14,27,0,24,3,108
6050,3,12,2,12,28,8,0,1,67,7,...,2,2,0,0,2,10,0,8,2,36
6051,5,11,1,11,21,7,0,0,62,6,...,2,2,0,0,1,9,0,7,2,37

In [11]:
# Display the dependent variable data
dependent = df[['defect']]
dependent

      defect
0          0
1          0
2          1
3          0
4          1
...      ...
6047       1
6048       0
6049       1
6050       0
6051       1

[6052 rows x 1 columns]

In [12]:
# Doing train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.2, random_state = 0)

In [13]:
# Implementing the RandomForestRegressor method
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 50, random_state = 0)
regressor.fit(X_train, y_train)

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

RandomForestRegressor(n_estimators=50, random_state=0)

In [14]:
# Predicting the values
y_pred = regressor.predict(X_test)

In [15]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.1260322333192858

In [16]:
#importing pickle library for deployment phase
import pickle

In [17]:
#here we are assigning the saving model file name with extension to the filename variable
filename = "finalized-model_CapstoneDefectPrediction.sav"
#using pickle dump method we are writing the file on disk
pickle.dump(regressor, open(filename, 'wb'))

In [18]:
#loading the saved model to loaded_variable.
loaded_model = pickle.load(open("finalized-model_CapstoneDefectPrediction.sav", 'rb'))

In [19]:
#here we are pedicting the value like we want and assigning to result variable.
result = loaded_model.predict([[14, 7, 1, 11, 3, 3, 1, 0, 32, 5, 0, 2, 0, 0, 2, 0, 4, 0, 5, 1, 38]])

C:\Anaconda3\envs\aiml\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [20]:
#displaying the predicted value for the given 5 values.
result[0]

0.48