In [1]:
# Importing the required library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Loading the dataset
dataset = pd.read_csv("DillibabuSarva_DefectDataset.csv")
dataset

,SHA,cbo,wmc,dit,rfc,lcom,totalMethods,totalFields,nosi,loc,...,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocks,uniqueWordsQty,defect
0,7a955fd6c7de2bd912be544dcfe77f9173a7aa600,5,60,2,55,189,27,5,30,247,...,4,2,47,9,27,5,17,3,191,0
1,000f1ab4780fc9460975791c52597f7c04e15be70,3,10,1,1,9,7,4,1,38,...,0,0,0,22,4,0,4,2,69,0
2,000f1ab4780fc9460975791c52597f7c04e15be71,3,10,1,1,9,7,4,0,38,...,0,0,0,22,4,0,4,2,69,1
3,0024dbdd6ba3cc7797cc0b1ae537dcdc488c4c270,20,59,3,63,189,24,9,4,262,...,0,6,6,14,45,8,41,4,222,0
4,0024dbdd6ba3cc7797cc0b1ae537dcdc488c4c271,21,58,2,61,189,24,9,0,260,...,0,6,6,14,45,8,41,4,222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6047,ffd1ed788cbf10bed00d49d79c7ee44250c36ac11,52,124,12,144,963,110,9,0,804,...,0,0,26,16,32,4,30,6,689,1
6048,ffdf4a3fcccb7489548c6a2ff6af7cebc92a180c0,24,27,2,46,4,8,8,0,126,...,0,1,3,14,27,0,24,3,108,0
6049,ffdf4a3fcccb7489548c6a2ff6af7cebc92a180c1,22,27,1,46,4,8,8,0,126,...,0,1,3,14,27,0,24,3,108,1
6050,ffe7c9989a4553d35fd1d5041d0cece0a673a0c80,3,12,2,12,28,8,0,1,67,...,2,0,0,2,10,0,8,2,36,0
6051,ffe7c9989a4553d35fd1d5041d0cece0a673a0c81,5,11,1,11,21,7,0,0,62,...,2,0,0,1,9,0,7,2,37,1

In [3]:
# Removing the first column
dataset.drop('SHA', axis = 1, inplace = True)

In [4]:
# Displaying the rows and columns count
dataset.shape

(6052, 22)

In [5]:
dataset.columns

Index(['cbo', 'wmc', 'dit', 'rfc', 'lcom', 'totalMethods', 'totalFields',
       'nosi', 'loc', 'returnQty', 'loopQty', 'comparisonsQty', 'tryCatchQty',
       'parenthesizedExpsQty', 'stringLiteralsQty', 'numbersQty',
       'assignmentsQty', 'mathOperationsQty', 'variablesQty',
       'maxNestedBlocks', 'uniqueWordsQty', 'defect'],
      dtype='object')

In [6]:
# Display the independent variable data
independent = dataset[['cbo', 'wmc', 'dit', 'rfc', 'lcom', 'totalMethods', 'totalFields',
       'nosi', 'loc', 'returnQty', 'loopQty', 'comparisonsQty', 'tryCatchQty',
       'parenthesizedExpsQty', 'stringLiteralsQty', 'numbersQty',
       'assignmentsQty', 'mathOperationsQty', 'variablesQty',
       'maxNestedBlocks', 'uniqueWordsQty']]
independent

,cbo,wmc,dit,rfc,lcom,totalMethods,totalFields,nosi,loc,returnQty,...,comparisonsQty,tryCatchQty,parenthesizedExpsQty,stringLiteralsQty,numbersQty,assignmentsQty,mathOperationsQty,variablesQty,maxNestedBlocks,uniqueWordsQty
0,5,60,2,55,189,27,5,30,247,25,...,9,4,2,47,9,27,5,17,3,191
1,3,10,1,1,9,7,4,1,38,7,...,2,0,0,0,22,4,0,4,2,69
2,3,10,1,1,9,7,4,0,38,7,...,2,0,0,0,22,4,0,4,2,69
3,20,59,3,63,189,24,9,4,262,12,...,16,0,6,6,14,45,8,41,4,222
4,21,58,2,61,189,24,9,0,260,12,...,15,0,6,6,14,45,8,41,4,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6047,52,124,12,144,963,110,9,0,804,20,...,3,0,0,26,16,32,4,30,6,689
6048,24,27,2,46,4,8,8,0,126,3,...,8,0,1,3,14,27,0,24,3,108
6049,22,27,1,46,4,8,8,0,126,3,...,8,0,1,3,14,27,0,24,3,108
6050,3,12,2,12,28,8,0,1,67,7,...,2,2,0,0,2,10,0,8,2,36
6051,5,11,1,11,21,7,0,0,62,6,...,2,2,0,0,1,9,0,7,2,37

In [7]:
# Display the dependent variable data
dataset[['defect']] = dataset[['defect']].astype('category')
dependent = dataset[['defect']]
print(dependent)

     defect
0         0
1         0
2         1
3         0
4         1
...     ...
6047      1
6048      0
6049      1
6050      0
6051      1

[6052 rows x 1 columns]

In [8]:
# Doing train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.2, random_state = 0)

In [9]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.datasets import make_hastie_10_2
classifier = HistGradientBoostingClassifier(max_iter=100).fit(X_train, y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [10]:
# Predicting the values
y_pred = classifier.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [12]:
print(cm)

[[432 148]
 [136 495]]

In [13]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)

In [14]:
#Random Forest classification report
print(clf_report)

              precision    recall  f1-score   support

           0       0.76      0.74      0.75       580
           1       0.77      0.78      0.78       631

    accuracy                           0.77      1211
   macro avg       0.77      0.76      0.76      1211
weighted avg       0.77      0.77      0.77      1211

In [15]:
#importing pickle library for deployment phase
import pickle

In [16]:
#here we are assigning the saving model file name with extension to the filename variable
filename = "finalized-model_CapstoneSoftwareDefectPrediction.sav"
#using pickle dump method we are writing the file on disk
pickle.dump(classifier, open(filename, 'wb'))

In [17]:
#here we are pedicting the value like we want and assigning to result variable.
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict([[14, 7, 1, 11, 3, 3, 1, 0, 32, 5, 0, 2, 0, 0, 2, 0, 4, 0, 5, 1, 38]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names
  warnings.warn(

In [18]:
#displaying the predicted value for the given 5 values.
result[0]

1

In [19]:
from sklearn.inspection import permutation_importance
# Calculate permutation importance
result = permutation_importance(
    loaded_model, X_train, y_train, n_repeats=10, random_state=42
)

# Create the DataFrame using the mean importances
importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': result.importances_mean
}).sort_values('Importance', ascending=False)

print(importance)

                 Feature  Importance
7                   nosi    0.290064
2                    dit    0.075150
8                    loc    0.041128
0                    cbo    0.031729
17     mathOperationsQty    0.019376
16        assignmentsQty    0.016567
9              returnQty    0.016257
3                    rfc    0.014935
12           tryCatchQty    0.012580
4                   lcom    0.012270
14     stringLiteralsQty    0.011857
18          variablesQty    0.011299
11        comparisonsQty    0.010762
1                    wmc    0.008944
15            numbersQty    0.007519
6            totalFields    0.007498
20        uniqueWordsQty    0.006796
5           totalMethods    0.005495
10               loopQty    0.004297
19       maxNestedBlocks    0.003760
13  parenthesizedExpsQty    0.003429