In [1]:
# Importing the required library
import pandas as pd
from Univariate import Univariate

In [2]:
# Loading the dataset
dataset = pd.read_csv("House_Price_Prediction.csv")
dataset

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
0,2014-05-02,313000.00,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,233.58
1,2014-05-02,2384000.00,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,653.15
2,2014-05-02,342000.00,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,177.20
3,2014-05-02,420000.00,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,210.00
4,2014-05-02,550000.00,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,283.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09,308166.67,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,204.08
4596,2014-07-09,534333.33,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,365.98
4597,2014-07-09,416904.17,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,138.51
4598,2014-07-10,203400.00,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,97.32
4599,2014-07-10,220600.00,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,148.05

In [3]:
# Displaying the rows and columns count
dataset.shape

(4600, 18)

In [4]:
quan,qual=Univariate.quanQual(dataset)

In [5]:
quan

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'price_per_sqft']

In [6]:
qual

['date', 'street', 'city', 'statezip']

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4600 non-null   object
 1   price           4600 non-null   float64
 2   bedrooms        4600 non-null   float64
 3   bathrooms       4600 non-null   float64
 4   sqft_living     4600 non-null   int64
 5   sqft_lot        4600 non-null   int64
 6   floors          4600 non-null   float64
 7   waterfront      4600 non-null   int64
 8   view            4600 non-null   int64
 9   condition       4600 non-null   int64
 10  sqft_above      4600 non-null   int64
 11  sqft_basement   4600 non-null   int64
 12  yr_built        4600 non-null   int64
 13  yr_renovated    4600 non-null   int64
 14  street          4600 non-null   object
 15  city            4600 non-null   object
 16  statezip        4600 non-null   object
 17  price_per_sqft  4600 non-null   float64
dtypes: float64(5), int64(9), object(4)
memory usage: 647.0+ KB

In [8]:
# Display the quantitative dataset
df = dataset[quan]
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,price_per_sqft
0,313000.00,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,233.58
1,2384000.00,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,653.15
2,342000.00,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,177.20
3,420000.00,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,210.00
4,550000.00,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,283.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,308166.67,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,204.08
4596,534333.33,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,365.98
4597,416904.17,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,138.51
4598,203400.00,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,97.32
4599,220600.00,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,148.05

In [9]:
# Display the dataset columns
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'price_per_sqft'],
      dtype='object')

In [10]:
# Display the independent variable data
independent = df[['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'price_per_sqft']]
independent

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,price_per_sqft
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,233.58
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,653.15
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,177.20
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,210.00
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,283.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,204.08
4596,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,365.98
4597,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,138.51
4598,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,97.32
4599,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,148.05

In [11]:
# Display the dependent variable data
dependent = df[['price']]
dependent

           price
0      313000.00
1     2384000.00
2      342000.00
3      420000.00
4      550000.00
...          ...
4595   308166.67
4596   534333.33
4597   416904.17
4598   203400.00
4599   220600.00

[4600 rows x 1 columns]

In [12]:
# Doing train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.2, random_state = 0)

In [13]:
# Implementing the RandomForestRegressor method
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 50, random_state = 0)
regressor.fit(X_train, y_train)

C:\Anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

RandomForestRegressor(n_estimators=50, random_state=0)

In [14]:
# Predicting the values
y_pred = regressor.predict(X_test)

In [15]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.9662875362535703

In [16]:
#importing pickle library for deployment phase
import pickle

In [17]:
#here we are assigning the saving model file name with extension to the filename variable
filename = "finalized-model_CapstoneRandomForest.sav"
#using pickle dump method we are writing the file on disk
pickle.dump(regressor, open(filename, 'wb'))

In [18]:
#loading the saved model to loaded_variable.
loaded_model = pickle.load(open("finalized-model_CapstoneRandomForest.sav", 'rb'))

In [19]:
#here we are pedicting the value like we want and assigning to result variable.
result = loaded_model.predict([[3, 2, 900, 6500, 2, 0, 0, 3, 900, 0, 1940, 1964, 600.50]])

C:\Anaconda3\envs\aiml\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [20]:
#displaying the predicted value for the given 5 values.
result[0]

523320.0